// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9qFmbabEsW394uSpWPiIgB5-bSLTcZBY',
    appId: '1:398232427571:web:f49d4aa53ea08919ed1746',
    messagingSenderId: '398232427571',
    projectId: 'firestoredb-dcb48',
    authDomain: 'firestoredb-dcb48.firebaseapp.com',
    storageBucket: 'firestoredb-dcb48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1RY_HCuJLp1s6yVnV-fyD7fV_v5kHos',
    appId: '1:398232427571:android:806cc30d0d57dadced1746',
    messagingSenderId: '398232427571',
    projectId: 'firestoredb-dcb48',
    storageBucket: 'firestoredb-dcb48.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClTHgwzmBKIav4xNBZoXQAaVkYCdSIR84',
    appId: '1:398232427571:ios:2081847eca9988feed1746',
    messagingSenderId: '398232427571',
    projectId: 'firestoredb-dcb48',
    storageBucket: 'firestoredb-dcb48.appspot.com',
    iosBundleId: 'com.teamcoderedex.codeRedexSih2023.RunnerTests',
  );
}
